name: Test

on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      run_codecov: ${{ matrix.os == 'ubuntu-latest' }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "1.10"
        arch:
          - "default"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        allow_failure: [false]
